
// Flipbook Actions
export const FLIPBOOK_SET = 'FLIPBOOK_SET_NAME';

// Brush Actions
export const BRUSH_COLOR_SET = 'BRUSH_COLOR_SET';
export const ERASER_COLOR_SET = 'ERASER_COLOR_SET';
export const SELECTED_TOOL_SET = 'SELECTED_TOOL_SET';
export const BRUSH_SIZE_SET = 'BRUSH_SIZE_SET';
export const BRUSH_POS_SET = 'BRUSH_POS_SET';
export const CAN_PAINT_TOGGLE = 'CAN_PAINT_TOGGLE';
export const SCALE_FACTOR_SET = 'SCALE_FACTOR_SET';

// Canvas Actions
export const CANVAS_SAVE = 'CANVAS_SAVE';
export const CANVAS_UNDO = 'CANVAS_UNDO';
export const CANVAS_REDO = 'CANVAS_REDO';
export const CANVAS_INITIALIZE = 'CANVAS_INITIALIZE';
export const CANVAS_ADD_FRAME = 'CANVAS_ADD_FRAME';
export const CANVAS_REMOVE_FRAME = 'CANVAS_REMOVE_FRAME';
export const CANVAS_UPDATE_MAX_COUNT = 'CANVAS_UPDATE_MAX_COUNT';
export const CANVAS_UPDATE_CURR_FRAME = 'CANVAS_UPDATE_CURR_FRAME';

// Lightbox Actions
export const LIGHTBOX_TOGGLE_ACTIVE = 'LIGHTBOX_TOGGLE_ACTIVE';
export const LIGHTBOX_SET_FRAME_COUNT = 'LIGHTBOX_SET_FRAME_COUNT';

// Animation Actions
export const ANIMATION_SET_ACTIVE = 'ANIMAION_SET_ACTIVE';
export const ANIMATION_SET_INACTIVE = 'ANIMATION_SET_INACTIVE';

// Dimmer Actions
export const DIMMER_TOGGLE_DIMMER = 'DIMMER_TOGGLE_DIMMER';