
// Brush Actions
export const BRUSH_COLOR_SET = 'BRUSH_COLOR_SET';
export const ERASER_COLOR_SET = 'ERASER_COLOR_SET';
export const SELECTED_TOOL_SET = 'SELECTED_TOOL_SET';
export const BRUSH_SIZE_SET = 'BRUSH_SIZE_SET';
export const BRUSH_POS_SET = 'BRUSH_POS_SET';
export const CAN_PAINT_TOGGLE = 'CAN_PAINT_TOGGLE';
export const SCALE_FACTOR_SET = 'SCALE_FACTOR_SET';
export const CURR_CANVAS_SAVE_IMG_DATA = 'CURR_CANVAS_SAVE_IMG_DATA';
